fix it again?!?

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,27 +1,45 @@
-language: csharp
-env:  
-  - CLI_VERSION=latest
+language: generic
+
 matrix:
   include:
-    - os: linux # Ubuntu 14.04
-      dist: trusty
+    - os: linux
+      dist: trusty # Ubuntu 14.04
       sudo: required
-      mono: latest
+    - os: osx
+      osx_image: xcode8 # macOS 10.11
 
-    - os: osx # OSX 10.11
-      osx_image: xcode8
-      mono: latest
-      before_install: 
-        - brew update
-        - brew install openssl
-        - mkdir -p /usr/local/lib
-        - ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
-        - ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
-install:  
+before_install:
+  # Install OpenSSL
+  - if test "$TRAVIS_OS_NAME" == "osx"; then
+      brew install openssl;
+      brew link --force openssl;
+      export DOTNET_SDK_URL="https://go.microsoft.com/fwlink/?LinkID=809128";
+    else
+      export DOTNET_SDK_URL="https://go.microsoft.com/fwlink/?LinkID=809129";
+    fi
+
   - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
-  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
+
+  # Install .NET CLI
+  - mkdir $DOTNET_INSTALL_DIR
+  - curl -L $DOTNET_SDK_URL -o dotnet_package
+  - tar -xvzf dotnet_package -C $DOTNET_INSTALL_DIR
+
+  # Add dotnet to PATH
   - export PATH="$DOTNET_INSTALL_DIR:$PATH"
-  - dotnet --info
-      
+
+install:
+  # Display dotnet version info
+  - which dotnet;
+    if [ $? -eq 0 ]; then
+      echo "Using dotnet:";
+      dotnet --info;
+    else
+      echo "dotnet.exe not found"
+      exit 1;
+    fi
+
+  - make build
+
 script:
-  - make all
+  - make tests
