updates

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,21 +1,54 @@
-language: csharp
-mono: none
-dotnet: 1.0.0-preview2-003131
+language: generic
+
+addons:
+  apt:
+    packages:
+    - gettext
+    - libcurl4-openssl-dev
+    - libicu-dev
+    - libssl-dev
+    - libunwind8
+    - zlib1g
 
 matrix:
   include:
-    - os: linux # Ubuntu 14.04
-      dist: trusty
+    - os: linux
+      dist: trusty # Ubuntu 14.04
       sudo: required
-    - os: osx # OSX 10.11
-      osx_image: xcode7.2
-      before_install: 
-        - brew update
-        - brew install openssl
-        - mkdir -p /usr/local/lib
-        - ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
-        - ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
+    - os: osx
+      osx_image: xcode7.2 # macOS 10.11
+    
+before_install:
+  # Install OpenSSL
+  - if test "$TRAVIS_OS_NAME" == "osx"; then
+      brew install openssl;
+      brew link --force openssl;
+      export DOTNET_SDK_URL="https://go.microsoft.com/fwlink/?LinkID=809128";
+    else
+      export DOTNET_SDK_URL="https://go.microsoft.com/fwlink/?LinkID=809129";
+    fi
+
+  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
+
+  # Install .NET CLI
+  - mkdir $DOTNET_INSTALL_DIR
+  - curl -L $DOTNET_SDK_URL -o dotnet_package
+  - tar -xvzf dotnet_package -C $DOTNET_INSTALL_DIR
+
+  # Add dotnet to PATH
+  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
+
 install:
+# Display dotnet version info
+  - which dotnet;
+    if [ $? -eq 0 ]; then
+      echo "Using dotnet:";
+      dotnet --info;
+    else
+      echo "dotnet.exe not found"
+      exit 1;
+    fi
   - make build
+  
 script:
   - make tests
